export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

//donor
export const ADD_DONOR_REQUEST = "ADD_DONOR_REQUEST";
export const ADD_DONOR_SUCCESS = "ADD_DONOR_SUCCESS";
export const ADD_DONOR_FAIL = "ADD_DONOR_FAIL";

export const LIST_DONORS_REQUEST = "LIST_DONORS_REQUEST";
export const LIST_DONORS_SUCCESS = "LIST_DONORS_SUCCESS";
export const LIST_DONORS_FAIL = "LIST_DONORS_FAIL";
